#!/usr/bin/env bash
#/*
# +-------------------------------------------------------------------------+
# | RoundCube Webmail IMAP Client                                           |
# | Version 0.3-20090814                                                    |
# |                                                                         |
# | Copyright (C) 2005-2010, RoundCube Dev. - Switzerland                   |
# |                                                                         |
# | This program is free software; you can redistribute it and/or modify    |
# | it under the terms of the GNU General Public License version 2          |
# | as published by the Free Software Foundation.                           |
# |                                                                         |
# | This program is distributed in the hope that it will be useful,         |
# | but WITHOUT ANY WARRANTY; without even the implied warranty of          |
# | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           |
# | GNU General Public License for more details.                            |
# |                                                                         |
# | You should have received a copy of the GNU General Public License along |
# | with this program; if not, write to the Free Software Foundation, Inc., |
# | 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.             |
# |                                                                         |
# +-------------------------------------------------------------------------+
# | Author: Till Klampaeckel <till@php.net>                                 |
# +-------------------------------------------------------------------------+
#
# $Id$
#
#*/

THIS_DIR=$(pwd)
ROUNDCUBE_INSTALL="${THIS_DIR}/../" 
ROUNDCUBE_INSTALL=`cd "${ROUNDCUBE_INSTALL}";pwd`

www_dir=${ROUNDCUBE_INSTALL}/plugins
test_dir=${ROUNDCUBE_INSTALL}/tests
temp_dir=${ROUNDCUBE_INSTALL}/temp
php_dir=${ROUNDCUBE_INSTALL}/plugins
data_dir=${ROUNDCUBE_INSTALL}/plugins
cache_dir=${ROUNDCUBE_INSTALL}/temp

channel=pear.roundcube.net

ROUNDCUBE_PEAR="${THIS_DIR}/roundcube.conf"

PEAR_CMD=`which pear`
PEAR_CMD="${PEAR_CMD} -c ${ROUNDCUBE_PEAR}"


PEAR_TASK=$1
PEAR_PACKAGE=$2
VERBOSE="-vvv "


if [ "$PEAR_TASK" = 'setup-roundcube' ]; then

    SETUP_CMD="pear config-create ${ROUNDCUBE_INSTALL} ${THIS_DIR}/roundcube.conf"
    $SETUP_CMD

    $PEAR_CMD channel-discover pear.roundcube.net

    $PEAR_CMD config-set cache_dir $cache_dir
    $PEAR_CMD config-set test_dir $test_dir
    $PEAR_CMD config-set temp_dir $temp_dir
    $PEAR_CMD config-set data_dir $data_dir
    $PEAR_CMD config-set php_dir $php_dir
    $PEAR_CMD config-set www_dir $www_dir
    $PEAR_CMD config-set default_channel $channel
    #$PEAR_CMD config-set preferred_mirror $channel
    #$PEAR_CMD config-set master_server $channel

    echo "Created local PEAR config in ${THIS_DIR}/roundcube.conf."
    exit
fi

if [ ! -f $ROUNDCUBE_PEAR ]; then
    echo "Please run ${0} setup-roundcube first!"
    exit 1
fi

PEAR_CMD="pear -c ${THIS_DIR}/roundcube.conf ${PEAR_TASK} ${PEAR_PACKAGE}"

$PEAR_CMD